// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vanadium.Note.REST.Data;

#nullable disable

namespace Vanadium.Note.REST.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20260730071445_RemoveLabels")]
    partial class RemoveLabels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vanadium.Note.REST.Models.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenSuffix")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000000)
                        .HasColumnType("character varying(2000000)");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletionGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchiveRoot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeletionRoot")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentNoteId")
                        .HasColumnType("uuid");

                    b.Property<int>("ShareMode")
                        .HasColumnType("integer");

                    b.Property<string>("ShareToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt")
                        .HasFilter("\"ArchivedAt\" IS NOT NULL");

                    b.HasIndex("Content");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Content"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Content"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DeletedAt")
                        .HasFilter("\"DeletedAt\" IS NOT NULL");

                    b.HasIndex("ParentNoteId");

                    b.HasIndex("ShareToken")
                        .IsUnique()
                        .HasFilter("\"ShareToken\" IS NOT NULL");

                    b.HasIndex("Title", "ContentText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "ContentText"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title", "ContentText"), new[] { "gin_trgm_ops", "gin_trgm_ops" });

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NotePropertySelectedOption", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.HasKey("NoteId", "DefinitionId", "OptionId");

                    b.HasIndex("OptionId");

                    b.HasIndex("DefinitionId", "OptionId");

                    b.ToTable("NotePropertySelectedOptions");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NotePropertyValue", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<double?>("NumberValue")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("NoteId", "DefinitionId");

                    b.HasIndex("DefinitionId", "BoolValue");

                    b.HasIndex("DefinitionId", "DateValue");

                    b.HasIndex("DefinitionId", "NumberValue");

                    b.HasIndex("DefinitionId", "SelectedOptionId");

                    b.HasIndex("DefinitionId", "TextValue");

                    b.ToTable("NotePropertyValues");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.PropertyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PropertyDefinitions");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.PropertyOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PropertyOptions");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DefaultPageSize")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultSortBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultSortDir")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("LegacyContentSanitized")
                        .HasColumnType("boolean");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NoteItem", b =>
                {
                    b.HasOne("Vanadium.Note.REST.Models.NoteItem", "ParentNote")
                        .WithMany("ChildNotes")
                        .HasForeignKey("ParentNoteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentNote");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NotePropertySelectedOption", b =>
                {
                    b.HasOne("Vanadium.Note.REST.Models.PropertyOption", "Option")
                        .WithMany()
                        .HasForeignKey("DefinitionId", "OptionId")
                        .HasPrincipalKey("DefinitionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vanadium.Note.REST.Models.NotePropertyValue", "Value")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("NoteId", "DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NotePropertyValue", b =>
                {
                    b.HasOne("Vanadium.Note.REST.Models.PropertyDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vanadium.Note.REST.Models.NoteItem", "Note")
                        .WithMany("PropertyValues")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vanadium.Note.REST.Models.PropertyOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("DefinitionId", "SelectedOptionId")
                        .HasPrincipalKey("DefinitionId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Definition");

                    b.Navigation("Note");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.PropertyOption", b =>
                {
                    b.HasOne("Vanadium.Note.REST.Models.PropertyDefinition", "Definition")
                        .WithMany("Options")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NoteItem", b =>
                {
                    b.Navigation("ChildNotes");

                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.NotePropertyValue", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("Vanadium.Note.REST.Models.PropertyDefinition", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
